version: '3.8'

services:
  influxdb:
    image: influxdb:2.0
    container_name: mmm-influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=mmm-fund
      - DOCKER_INFLUXDB_INIT_BUCKET=strategy-monitoring
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token

  grafana:
    image: grafana/grafana:latest
    container_name: mmm-grafana
    ports:
      - "3001:3001"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    depends_on:
      - influxdb

  redis:
    image: redis:alpine
    container_name: mmm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # monitor:
  #   build: .
  #   command: ts-node src/scripts/startMonitoring.ts
  #   depends_on:
  #     - redis
  #     - influxdb

volumes:
  influxdb-data:
  grafana-data:
  redis-data: